# Generated by Django 6.0.3 on 2026-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEMApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('live', 'LIVE'), ('upcoming', 'UPCOMING'), ('end', 'END')], default='upcoming', max_length=10),
        ),
    ]
